import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>GooglySearchHS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>GooglyHS</h1>
		</div>
	);
}
